### ISSUE TITLE
.inspect in the global object

### ISSUE THREAD

**Issue by gmahomar** [node-machine/switchback#1]
I'm not sure if this is the expected behavior, but on this line:
https://github.com/balderdashy/switchback/blob/master/lib/factory.js#L42
```javascript
// Mix in non-enumerable `.inspect()` method
  Object.defineProperty(this, 'inspect', { enumerable: false, writable: true });
  _switch.inspect = function () { return '[Switchback]'; };
```

```this``` resolves to ```global```, adding ```inspect``` to the ```global``` object. This is a problem in one of our projects in which we're using [Lab](https://github.com/hapijs/lab) as our test runner. Lab tests for global variable leaks, and this is forcing us to disable it. 

Is inspect supposed to be part of the ```global``` object?

**Comment by devinivy** [comment]
I had the same issue using lab.  PR #2 should resolve this.

**Comment by sgress454** [comment]
Merged that PR, thanks fellas!
